### ISSUE TITLE
How does accessControl config map work?

### ISSUE THREAD

**Issue by mFeigeInvia** [valeriano-manassero/helm-charts#104]
Hi,
how is it possible to create the json, as I understand the file is called rules.json but it's content will be a property file?

https://github.com/valeriano-manassero/helm-charts/blob/e03e59041d68a3d93fb404a46627c4520b57ba83/valeriano-manassero/trino/templates/configmap-coordinator.yaml#L91

Thx for helping

**Comment by mFeigeInvia** [comment]
As always, after I wrote the issue, I found a solution. Might be be good for the documentation.
```
accessControl:
  type: configmap
  configFile: "rules.json"
  rules:
    rules.json: |-
     {}
```
