### ISSUE TITLE
Support different resources configuration for coordinator and worker

### ISSUE THREAD

**Issue by hebestreit** [valeriano-manassero/helm-charts#117]
I would like to set different resource configurations for the coordinator and the worker deployments.

If I would implement how it's done for the [initContainers](https://github.com/valeriano-manassero/helm-charts/blob/main/valeriano-manassero/trino/values.yaml#L67) it could look like below but this will result in a breaking change:

```
resources:
  coordinator:
     limits:
      cpu: 100m
      memory: 128Mi
     requests:
      cpu: 100m
      memory: 128Mi
  worker:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
```

Any ideas how to support it?
