### ISSUE TITLE
Connecting to Trino with Authentication enabled within the cluster

### ISSUE THREAD

**Issue by saikiran2603** [valeriano-manassero/helm-charts#136]
Hi , 

We have deployed trino helm chart and have enabled authentication for it , using below chart values. We are able to create an ingress and connect to trino via the ingress with credentials. But we were wondering how to connect to trino with authentication/ without authentication from within the cluster ? , as a work around we are currently connecting to trino via the ingress host name , but is there a way to connect within the cluster without routing via ingress  ? 

helm values.yaml 

```
auth:
   passwordAuth: "admin:<encodedvalues>"

config:
  general:
    processForwarded: true
    authenticationType: "PASSWORD"
    internalCommunicationSharedSecret: "test123"
ingress:
  enabled: false
```

Ingress definition 
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trino-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: trino.$HOST_NAME
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: trino
                port:
                  number: 8080
  tls:
    - hosts:
        - trino.$HOST_NAME
      secretName: tls-secret
```

Connecting to trino from inside the cluster 

```
            trino_connection = connect(
                host=trino_server,
                port=443,
                verify=False,
                auth=BasicAuthentication("admin", "pwd"),
                http_scheme="https",
                catalog="hive",
                schema="default",
            )
```
The above connection gets routed via the ingress definition, is there a way for us to connect to trino , from within the cluster without passing though the Ingress ?
