### ISSUE TITLE
[trino] Supporting more variables for securityContext for pod and container level.

### ISSUE THREAD

**Issue by hafizmujadidKhalid** [valeriano-manassero/helm-charts#189]
### Is your feature request related to a problem ?

Hey folks!

I am trying to deploy Trino using your provided helm chart but since our EKS cluster has some validations set it fails to deploy. The failing validations are like running with non_root_user and dropping all capabilities etc.   

### Describe the solution you'd like.

To fix it, I have to add following security context for container:
   ```
securityContext:
        allowPrivilegeEscalation: false
        capabilities:
            drop:
               - ALL
        runAsUser: 1000
```
and following for the pod:
```
     securityContext:
          runAsNonRoot: true
          seccompProfile:
              type: RuntimeDefault
```

I want to support general securityContext settings inside values.yaml file and they should be reflected in relevant deployments.  I would have created a PR but due to my limited knowledge of helm templating, I could not produce well-indented yaml. 

### Describe alternatives you've considered.

None, Our security team have these security & validation check in place and they are not willing to relax. I have to deploy rending template and modifying actual yaml files.
