### ISSUE TITLE
How to add group file ?

### ISSUE THREAD

**Issue by jeremyjouvancedev** [valeriano-manassero/helm-charts#92]
hi, 
How can i add the group file into the chart near schemas and connectors ?

Links: https://trino.io/docs/current/security/group-file.html

**Comment by valeriano-manassero** [comment]
Implementing something like this in vales should not be too much difficult:

```
userGroups:
  group1:
  - user_1
  - user_2
  - user_3
  group2:
  - user_4
  - user_5
  - user_6
 ```

If userGroups is not empty by default we can generate a configMap and mount it as a fine in coordinator. wdyt?
